version: '3.9'

services:
  postgres:
    image: postgres
    container_name: banking-postgres
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-banking_db}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SQL_USER:-postgres} -d ${SQL_DATABASE:-notifications}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking_network

networks:
  banking_network:
    driver: bridge

volumes:
  postgres_data: