services:
  postgres:
    image: debezium/postgres
    container_name: banking-postgres
    restart: always
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-banking_db}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - banking_network

networks:
  banking_network:
    driver: bridge

volumes:
  postgres_data: