services:
  zookeeper:
    image: zookeeper:3.9
    container_name: banking-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
      ZOO_TICK_TIME: 4000
      ZOO_INIT_LIMIT: 10
      ZOO_SYNC_LIMIT: 5
      ZOO_MAX_CLIENT_CNXNS: 60
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    restart: unless-stopped
    networks:
      - banking-net

  bookie1:
    image: apache/bookkeeper:4.17.0
    container_name: bookie1
    environment:
      BK_zkServers: zookeeper:2181
      BK_zkLedgersRootPath: /ledgers
      BK_journalDirectories: /data/journal
      BK_ledgerDirectories: /data/ledgers
      BK_indexDirectories: /data/index
      BK_bookiePort: 3181
      BK_useHostNameAsBookieID: "false"
      BK_bookieId: bookie1:3181
      BK_forceFormat: "true"
    volumes:
      - bk1-journal:/data/journal
      - bk1-ledgers:/data/ledgers
      - bk1-index:/data/index
    ports:
      - "3181:3181"
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - banking-net

#  bookie2:
#    image: apache/bookkeeper:4.17.0
#    container_name: bookie2
#    environment:
#      BK_zkServers: zookeeper:2181
#      BK_zkLedgersRootPath: /ledgers
#      BK_journalDirectories: /data/journal
#      BK_ledgerDirectories: /data/ledgers
#      BK_indexDirectories: /data/index
#      BK_bookiePort: 3181
#      BK_useHostNameAsBookieID: "false"
#      BK_bookieId: bookie2:3181
#      BK_forceFormat: "true"
#    volumes:
#      - bk2-journal:/data/journal
#      - bk2-ledgers:/data/ledgers
#      - bk2-index:/data/index
#    ports:
#      - "3182:3181"
#    restart: unless-stopped
#    depends_on:
#      - zookeeper
#    networks:
#      - banking-net
#
#  bookie3:
#    image: apache/bookkeeper:4.17.0
#    container_name: bookie3
#    environment:
#      BK_zkServers: zookeeper:2181
#      BK_zkLedgersRootPath: /ledgers
#      BK_journalDirectories: /data/journal
#      BK_ledgerDirectories: /data/ledgers
#      BK_indexDirectories: /data/index
#      BK_bookiePort: 3181
#      BK_useHostNameAsBookieID: "false"
#      BK_bookieId: bookie3:3181
#      BK_forceFormat: "true"
#    volumes:
#      - bk3-journal:/data/journal
#      - bk3-ledgers:/data/ledgers
#      - bk3-index:/data/index
#    ports:
#      - "3183:3181"
#    restart: unless-stopped
#    depends_on:
#      - zookeeper
#    networks:
#      - banking-net

volumes:
  zookeeper_data:
  zookeeper_datalog:
  bk1-journal:
  bk1-ledgers:
  bk1-index:
  bk2-journal:
  bk2-ledgers:
  bk2-index:
  bk3-journal:
  bk3-ledgers:
  bk3-index:

networks:
  banking-net:
    driver: bridge